### ISSUE TITLE
Document project plan

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/position-effect-correction#2]
## Benchmark

1. same well-position, different perturbation mAP - this should go down
2. same perturbation, different well-position mAP - this should go up
3. same perturbation, same well-position mAP - this will go down but we don't want it to go down by too muhc

- Exclude controls in all 3 cases
- Use notebooks in [evalzoo](https://github.com/cytomining/evalzoo/tree/main/matric) to produce metrics

## Dummy method

Add noise and compare with baseline

## Simple method

Mean subtract per-feature per-well position

## Complex method

Estimate the 16x24 function per feature using a CNN

**Comment by shntnu** [comment]
> I was able to successfully run metrics for this in #3

@alxndrkalinin two things to keep in mind

1. [Currently](https://github.com/broadinstitute/position-effect-correction/blob/cda9e242aebea8031bd01a5a358a2c3507f9f3cb/1.load/1-setup.ipynb) only two features are being used when collating the profiles (`Cells_AreaShape_Eccentricity`, `Nuclei_AreaShape_Area`). We need to use all.
2. We need to run the profiling workflow (normalization + feature selection) on the profiles after correction for this overall strategy to work. 

LMK if this doesn't make sense

**Comment by AnneCarpenter** [comment]
I'd love an update on ETA @alxndrkalinin (given I'm missing checkin this week!)

**Comment by shntnu** [comment]
Greg's method for filtering out features that are impacted by technical artifacts could be a simple way of identifying features that should be dumped. 

https://docs.google.com/document/d/1adINm2eJp31gjtqmPeODyTqyTG0hMY_UbcgBFUi2R1s/edit#heading=h.9p9irsx7s9go

(Constructing the resistance signature) 

The idea is very simple – fit a linear model, adjust for multiple testing, drop features that have high beta on covariates you want to factor out

**Comment by AnneCarpenter** [comment]
Interesting - in theory, I would always rather correct features if we can, rather than having a harsh filter that loses their info entirely. 

That raise a Q: one could imagine that after running a plate layout correction, it could increase the variation (across replicates) of a given feature, so we would want to be sure we do our feature-QC check *after* the plate layout correction step. At least I assume we have a 'feature QC check' of some sort early on in the workflow?

**Comment by shntnu** [comment]
> Interesting - in theory, I would always rather correct features if we can, rather than having a harsh filter that loses their info entirely.

Agreed

> That raise a Q: one could imagine that after running a plate layout correction, it could increase the variation (across replicates) of a given feature, so we would want to be sure we do our feature-QC check _after_ the plate layout correction step. At least I assume we have a 'feature QC check' of some sort early on in the workflow?

Yes, that aligns with what Alex has written down here https://github.com/broadinstitute/position-effect-correction/issues/2#issuecomment-1481785516

**Comment by alxndrkalinin** [comment]
Analysis of regressing out cell count from other features has been added in #15. I'm also going to test adding PCA on top of that, but otherwise we have no specific additional steps planned for position effect correction. 

@niranjchandrasekaran, do you think I should produce cell count corrected profiles for the next hackathon phase, so people can start using them, or are we still working on exploring and correcting QC issues that need to be addressed before sharing profiles?

**Comment by niranjchandrasekaran** [comment]
> do you think I should produce cell count corrected profiles for the next hackathon phase, so people can start using them,

It will be nice to have the cell count corrected profiles for the hackathon. Thanks Alex! Later, we can have other versions of the profiles once the other QC issues are resolved.

**Comment by AnneCarpenter** [comment]
The only other QC things we plan to deal with are things more likely to be handled by  "throw out this plate" rather than something more sophisticated; I don't think we will take the time to do things like try to salvage or filter individual rows or quadrant patterns that look weird. So I do think cell count regression can happen now and it will give enough info to know whether to do anything else beyond just discarding a few bad plates.
https://github.com/jump-cellpainting/morphmap/issues/6

**Comment by shntnu** [comment]
I'll close out this issue because been superseded by other issues in this repo
